sudo: required
dist: trusty
language: node_js
node_js:
  - '9.5.0'

before_script:
- npm install -g @angular/cli@latest typescript
- npm install

script: 
- ng lint --type-check
- ng build --prod --aot
